export type ShareLocale = "en-US" | "zh-CN";
export type ShareDevice = "desktop" | "mobile";
export type ShareView = "tex" | "pdf" | "comments";

export type ShareComment = {
  id: string;
  username: string;
  text: string;
  quote: string;
  source: "pdf" | "tex";
  sessionName: string;
  sessionCreatedAt: string;
  page?: number;
  start?: number;
  end?: number;
  createdAt: string;
};

export type ShareParticipant = {
  username?: string;
  lastAction?: string;
};

export type ShareQuote = {
  source: "tex" | "pdf";
  text: string;
  page?: number;
  start?: number;
  end?: number;
};

export type ShareI18n = {
  title: string;
  brand: string;
  identityLabel: string;
  passwordLabel: string;
  workspaceKicker: string;
  accessTitle: string;
  modesTitle: string;
  manuscriptKicker: string;
  previewKicker: string;
  editorPanelLabel: string;
  pdfPanelLabel: string;
  presenceKicker: string;
  discussionKicker: string;
  currentSelection: string;
  statusIdle: string;
  statusConnecting: string;
  statusConnected: string;
  statusPdfPreparing: string;
  statusPdfReady: string;
  statusNeedFields: string;
  statusQuoteNeeded: string;
  statusCommentPosted: string;
  connectedBadge: string;
  join: string;
  reloadPdf: string;
  copyPassword: string;
  copyPasswordDone: string;
  usernamePlaceholder: string;
  passwordPlaceholder: string;
  tabTex: string;
  tabPdf: string;
  tabComments: string;
  addQuote: string;
  quoteLabel: string;
  commentPlaceholder: string;
  postComment: string;
  clearQuote: string;
  inlineBadge: string;
  collaborators: string;
  comments: string;
  noCollaborators: string;
  noComments: string;
  noPdfPreview: string;
  quoteFromTex: string;
  clickJump: string;
  shareHint: string;
  actionReading: string;
  actionEditing: string;
  actionCommenting: string;
  actionCompile: string;
  promptNeedCommentOrQuote: string;
  editorPlaceholder: string;
  discussionPlaceholder: string;
  connectHelp: string;
  reviewSurface: string;
  livePresence: string;
  commentJump: string;
  sessionBadge: (sid: string) => string;
  missingSession: string;
  statusPdfLoadFailed: (reason: string) => string;
  statusPostCommentFailed: (reason: string) => string;
  statusCompileRequested: string;
  statusCompileFailed: (reason: string) => string;
  statusSyncFailed: (reason: string) => string;
  statusConnectFailed: (reason: string) => string;
  pdfPageLabel: (page: number, total: number) => string;
  quoteFromPdf: (page: number) => string;
};
