export function createWorkspaceEditorMonacoOptions(overflowWidgetsDomNode?: HTMLElement | null, fontScale = 1) {
  const scale = Math.max(0.85, Math.min(1.25, Number(fontScale) || 1));
  const fontSize = Math.round(14 * scale);
  return {
    minimap: { enabled: false },
    fontSize,
    fontLigatures: true,
    letterSpacing: 0,
    lineHeight: Math.round(22 * scale),
    lineNumbers: "on" as const,
    lineNumbersMinChars: 6,
    lineDecorationsWidth: 8,
    glyphMargin: false,
    folding: true,
    renderValidationDecorations: "on" as const,
    renderLineHighlight: "line" as const,
    renderLineHighlightOnlyWhenFocus: true,
    renderLineHighlightGutter: "all" as const,
    smoothScrolling: true,
    automaticLayout: true,
    quickSuggestions: { other: true, comments: false, strings: true },
    suggestOnTriggerCharacters: true,
    tabCompletion: "on" as const,
    inlineSuggest: { enabled: true, mode: "subword" as const },
    bracketPairColorization: { enabled: true },
    colorDecorators: false,
    acceptSuggestionOnCommitCharacter: true,
    wordWrap: "on" as const,
    wordWrapColumn: 0,
    wrappingIndent: "same" as const,
    padding: { top: 20, bottom: 96 },
    scrollBeyondLastLine: true,
    hideCursorInOverviewRuler: true,
    overviewRulerBorder: false,
    roundedSelection: true,
    selectionHighlight: false,
    cursorBlinking: "smooth" as const,
    cursorSmoothCaretAnimation: "on" as const,
    fixedOverflowWidgets: true,
    overflowWidgetsDomNode: overflowWidgetsDomNode ?? undefined,
    stickyScroll: { enabled: false },
    scrollbar: {
      verticalScrollbarSize: 10,
      horizontalScrollbarSize: 10,
      alwaysConsumeMouseWheel: false,
    },
  };
}
