export function createWorkspaceEditorMonacoOptions(overflowWidgetsDomNode?: HTMLElement | null) {
  return {
    minimap: { enabled: false },
    fontSize: 14,
    fontLigatures: true,
    letterSpacing: 0.15,
    lineHeight: 22,
    lineNumbers: "on" as const,
    lineNumbersMinChars: 4,
    lineDecorationsWidth: 12,
    glyphMargin: true,
    folding: true,
    renderValidationDecorations: "on" as const,
    renderLineHighlight: "line" as const,
    renderLineHighlightOnlyWhenFocus: true,
    renderLineHighlightGutter: "all" as const,
    smoothScrolling: true,
    automaticLayout: true,
    quickSuggestions: { other: true, comments: false, strings: true },
    suggestOnTriggerCharacters: true,
    tabCompletion: "on" as const,
    inlineSuggest: { enabled: true, mode: "subword" as const },
    bracketPairColorization: { enabled: true },
    colorDecorators: false,
    acceptSuggestionOnCommitCharacter: true,
    wordWrap: "on" as const,
    wordWrapColumn: 0,
    wrappingIndent: "same" as const,
    padding: { top: 20, bottom: 28 },
    scrollBeyondLastLine: false,
    hideCursorInOverviewRuler: true,
    overviewRulerBorder: false,
    roundedSelection: true,
    selectionHighlight: false,
    cursorBlinking: "smooth" as const,
    cursorSmoothCaretAnimation: "on" as const,
    fixedOverflowWidgets: true,
    overflowWidgetsDomNode: overflowWidgetsDomNode ?? undefined,
    stickyScroll: { enabled: false },
    scrollbar: {
      verticalScrollbarSize: 10,
      horizontalScrollbarSize: 10,
      alwaysConsumeMouseWheel: false,
    },
  };
}
