use crate::models::ResearchCapabilityDescriptor;
use serde_json::{json, Value};

struct CapabilitySeed {
    id: &'static str,
    risk: &'static str,
    target: &'static str,
    resource_mode: Option<&'static str>,
    idempotency: &'static str,
    timeout_ms: u64,
    max_retries: u32,
    undo_capability: Option<&'static str>,
    egress_category: &'static str,
}

const CAPABILITIES: &[CapabilitySeed] = &[
    seed(
        "project.overview",
        "read",
        "backend",
        None,
        "safe_replay",
        15_000,
        1,
        None,
        "none",
    ),
    seed(
        "ui.navigate",
        "read",
        "frontend",
        None,
        "safe_replay",
        15_000,
        0,
        None,
        "none",
    ),
    seed(
        "literature.search",
        "read",
        "backend",
        None,
        "request_deduplicated",
        120_000,
        2,
        None,
        "academic_metadata",
    ),
    seed(
        "literature.import",
        "write",
        "frontend",
        Some("write"),
        "result_keyed",
        120_000,
        0,
        None,
        "academic_metadata",
    ),
    seed(
        "literature.open",
        "read",
        "frontend",
        Some("read"),
        "safe_replay",
        15_000,
        0,
        None,
        "none",
    ),
    seed(
        "literature.citation_trace",
        "read",
        "frontend",
        None,
        "request_deduplicated",
        120_000,
        1,
        None,
        "academic_metadata",
    ),
    seed(
        "workspace.read",
        "read",
        "backend",
        Some("read"),
        "safe_replay",
        30_000,
        1,
        None,
        "none",
    ),
    seed(
        "workspace.propose_latex",
        "write",
        "frontend",
        Some("write"),
        "result_keyed",
        180_000,
        0,
        None,
        "none",
    ),
    seed(
        "workspace.apply_latex",
        "write",
        "frontend",
        Some("write"),
        "checkpointed_write",
        120_000,
        0,
        Some("research.checkpoint.undo"),
        "none",
    ),
    seed(
        "workspace.write_non_latex",
        "high",
        "frontend",
        Some("write"),
        "never_replay",
        120_000,
        0,
        None,
        "none",
    ),
    seed(
        "workspace.compile",
        "read",
        "frontend",
        Some("read"),
        "request_deduplicated",
        300_000,
        0,
        None,
        "none",
    ),
    seed(
        "analysis.run",
        "read",
        "frontend",
        Some("read"),
        "result_keyed",
        900_000,
        0,
        None,
        "none",
    ),
    seed(
        "report.generate",
        "read",
        "frontend",
        None,
        "result_keyed",
        120_000,
        0,
        None,
        "none",
    ),
    seed(
        "report.export",
        "write",
        "frontend",
        Some("write"),
        "result_keyed",
        120_000,
        0,
        None,
        "none",
    ),
    seed(
        "draw.create",
        "write",
        "frontend",
        Some("write"),
        "result_keyed",
        60_000,
        0,
        None,
        "none",
    ),
    seed(
        "draw.open",
        "read",
        "frontend",
        Some("read"),
        "safe_replay",
        15_000,
        0,
        None,
        "none",
    ),
    seed(
        "draw.export",
        "write",
        "frontend",
        Some("write"),
        "result_keyed",
        120_000,
        0,
        None,
        "none",
    ),
    seed(
        "submission.check",
        "read",
        "backend",
        Some("read"),
        "safe_replay",
        120_000,
        1,
        None,
        "none",
    ),
    seed(
        "submission.build",
        "high",
        "frontend",
        Some("write"),
        "never_replay",
        300_000,
        0,
        None,
        "none",
    ),
    seed(
        "submission.send",
        "high",
        "frontend",
        None,
        "never_replay",
        300_000,
        0,
        None,
        "external_submission",
    ),
    seed(
        "git.status",
        "read",
        "frontend",
        None,
        "safe_replay",
        30_000,
        0,
        None,
        "none",
    ),
    seed(
        "git.diff",
        "read",
        "frontend",
        Some("read"),
        "safe_replay",
        60_000,
        0,
        None,
        "none",
    ),
    seed(
        "git.commit",
        "high",
        "frontend",
        Some("write"),
        "never_replay",
        120_000,
        0,
        None,
        "none",
    ),
    seed(
        "runtime.status",
        "read",
        "backend",
        None,
        "safe_replay",
        15_000,
        1,
        None,
        "none",
    ),
    seed(
        "runtime.update",
        "high",
        "frontend",
        None,
        "never_replay",
        600_000,
        0,
        None,
        "runtime_download",
    ),
    seed(
        "plugin.status",
        "read",
        "frontend",
        None,
        "safe_replay",
        30_000,
        0,
        None,
        "none",
    ),
    seed(
        "plugin.update",
        "high",
        "frontend",
        None,
        "never_replay",
        600_000,
        0,
        None,
        "plugin_download",
    ),
    seed(
        "settings.change",
        "high",
        "frontend",
        None,
        "never_replay",
        60_000,
        0,
        None,
        "none",
    ),
];

const fn seed(
    id: &'static str,
    risk: &'static str,
    target: &'static str,
    resource_mode: Option<&'static str>,
    idempotency: &'static str,
    timeout_ms: u64,
    max_retries: u32,
    undo_capability: Option<&'static str>,
    egress_category: &'static str,
) -> CapabilitySeed {
    CapabilitySeed {
        id,
        risk,
        target,
        resource_mode,
        idempotency,
        timeout_ms,
        max_retries,
        undo_capability,
        egress_category,
    }
}

fn object_schema(properties: Value, required: &[&str]) -> Value {
    json!({
        "type": "object",
        "properties": properties,
        "required": required,
        "additionalProperties": false,
    })
}

fn capability_input_schema(id: &str) -> Value {
    let string = || json!({ "type": "string", "maxLength": 4096 });
    let path =
        || json!({ "type": "string", "format": "workspace-relative-path", "maxLength": 1024 });
    let strings = || json!({ "type": "array", "items": { "type": "string", "maxLength": 4096 }, "maxItems": 16 });
    match id {
        "project.overview" | "git.status" | "runtime.status" | "plugin.status" => {
            object_schema(json!({}), &[])
        }
        "ui.navigate" => object_schema(
            json!({ "pageId": string(), "resource": path() }),
            &["pageId"],
        ),
        "literature.search" => object_schema(
            json!({ "queries": strings(), "deep": { "type": "boolean" } }),
            &["queries"],
        ),
        "literature.import" => object_schema(json!({ "source": string() }), &["source"]),
        "literature.open" => object_schema(json!({ "path": path() }), &["path"]),
        "literature.citation_trace" => object_schema(
            json!({ "doi": string(), "direction": { "type": "string", "enum": ["forward", "backward", "both"] } }),
            &["doi", "direction"],
        ),
        "workspace.read" => object_schema(
            json!({ "path": path(), "maxChars": { "type": "integer", "minimum": 256, "maximum": 32768 } }),
            &["path"],
        ),
        "workspace.propose_latex" => object_schema(
            json!({ "path": path(), "instruction": string() }),
            &["path", "instruction"],
        ),
        "workspace.apply_latex" => object_schema(
            json!({ "path": path(), "proposalId": string() }),
            &["path", "proposalId"],
        ),
        "workspace.write_non_latex" => object_schema(
            json!({ "path": path(), "content": { "type": "string", "maxLength": 1048576 } }),
            &["path", "content"],
        ),
        "workspace.compile" | "submission.check" | "submission.build" => object_schema(
            json!({ "mainPath": path(), "profileId": string() }),
            &["mainPath"],
        ),
        "analysis.run" => object_schema(
            json!({
                "prompt": string(),
                "inputFiles": { "type": "array", "items": path(), "maxItems": 8 },
                "spec": {
                    "type": "object",
                    "properties": {
                        "methodFamily": {
                            "type": "string",
                            "enum": [
                                "descriptive", "group_comparison", "relationship",
                                "linear_regression", "logistic_regression",
                                "poisson_regression", "glm", "mixed_model",
                                "survival", "time_series", "meta_analysis", "power_analysis"
                            ]
                        },
                        "outcome": string(),
                        "predictors": { "type": "array", "items": string(), "maxItems": 32 },
                        "covariates": { "type": "array", "items": string(), "maxItems": 32 },
                        "groupColumn": string(),
                        "subjectColumn": string(),
                        "timeColumn": string(),
                        "eventColumn": string(),
                        "effectColumn": string(),
                        "standardErrorColumn": string(),
                        "glmFamily": { "type": "string", "enum": ["gaussian", "binomial", "poisson"] },
                        "glmLink": { "type": "string", "enum": ["identity", "logit", "log"] },
                        "missingValueStrategy": { "type": "string", "enum": ["complete_case", "report_only"] },
                        "transformationStrategy": { "type": "string", "enum": ["none", "log", "standardize"] },
                        "outlierStrategy": { "type": "string", "enum": ["report_only", "exclude_iqr"] },
                        "multipleComparisonStrategy": { "type": "string", "enum": ["none", "benjamini_hochberg"] },
                        "alpha": { "type": "number", "exclusiveMinimum": 0, "exclusiveMaximum": 1 },
                        "power": {
                            "type": "object",
                            "properties": {
                                "effectSize": { "type": "number" },
                                "targetPower": { "type": "number" },
                                "groupRatio": { "type": "number" },
                                "alternative": { "type": "string", "enum": ["two-sided", "larger", "smaller"] }
                            },
                            "required": ["effectSize", "targetPower"],
                            "additionalProperties": false
                        },
                        "randomSeed": { "type": "integer", "minimum": 1 },
                        "rationale": string()
                    },
                    "required": [
                        "methodFamily", "missingValueStrategy", "transformationStrategy",
                        "outlierStrategy", "multipleComparisonStrategy", "alpha", "randomSeed", "rationale"
                    ],
                    "additionalProperties": false
                }
            }),
            &["prompt", "inputFiles"],
        ),
        "report.generate" => object_schema(json!({ "title": string() }), &["title"]),
        "report.export" => object_schema(
            json!({ "reportId": string(), "format": string() }),
            &["reportId", "format"],
        ),
        "draw.create" => object_schema(json!({ "name": string() }), &["name"]),
        "draw.open" => object_schema(json!({ "path": path() }), &["path"]),
        "draw.export" => object_schema(
            json!({ "path": path(), "format": string() }),
            &["path", "format"],
        ),
        "submission.send" => object_schema(
            json!({ "artifactId": string(), "channel": string() }),
            &["artifactId", "channel"],
        ),
        "git.diff" => object_schema(json!({ "path": path() }), &[]),
        "git.commit" => object_schema(
            json!({ "message": string(), "paths": { "type": "array", "items": path(), "maxItems": 64 } }),
            &["message", "paths"],
        ),
        "runtime.update" => object_schema(
            json!({ "runtimeId": { "type": "string", "enum": ["codex-cli", "claude-code-cli"] } }),
            &["runtimeId"],
        ),
        "plugin.update" => object_schema(json!({ "pluginId": string() }), &["pluginId"]),
        "settings.change" => object_schema(json!({ "patch": { "type": "object" } }), &["patch"]),
        _ => object_schema(json!({}), &[]),
    }
}

pub(super) fn capability_registry() -> Vec<ResearchCapabilityDescriptor> {
    CAPABILITIES
        .iter()
        .map(|seed| ResearchCapabilityDescriptor {
            id: seed.id.to_string(),
            input_schema: capability_input_schema(seed.id),
            output_type: "json".to_string(),
            risk_level: seed.risk.to_string(),
            risk_reason_key: format!("research.capability.risk.{}", seed.risk),
            execution_target: seed.target.to_string(),
            auto_after_plan_approval: seed.risk != "high",
            resource_mode: seed.resource_mode.map(str::to_string),
            idempotency: seed.idempotency.to_string(),
            timeout_ms: seed.timeout_ms,
            max_retries: seed.max_retries,
            undo_capability: seed.undo_capability.map(str::to_string),
            egress_category: seed.egress_category.to_string(),
            requires_network: seed.egress_category != "none",
        })
        .collect()
}
